<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ChiTietDonHangSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('chi_tiet_don_hangs')->delete();
        DB::table('chi_tiet_don_hangs')->truncate();
        DB::table('chi_tiet_don_hangs')->insert([
            [
                'id_don_hang'    => 0,
                'id_khach_hang'  => 1,
                'id_mon_an'      => 12,
                'id_quan_an'     => 3,
                'so_luong'       => 1,
                'don_gia'        => 25000,
                'thanh_tien'     => 25000,
            ],
            [
                'id_don_hang'    => 0,
                'id_khach_hang'  => 2,
                'id_mon_an'      => 7,
                'id_quan_an'     => 2,
                'so_luong'       => 1,
                'don_gia'        => 20000,
                'thanh_tien'     => 20000,
            ],
            [
                'id_don_hang'    => 0,
                'id_khach_hang'  => 3,
                'id_mon_an'      => 26,
                'id_quan_an'     => 7,
                'so_luong'       => 1,
                'don_gia'        => 40000,
                'thanh_tien'     => 40000,
            ],
            [
                'id_don_hang'    => 0,
                'id_khach_hang'  => 4,
                'id_mon_an'      => 33,
                'id_quan_an'     => 9,
                'so_luong'       => 1,
                'don_gia'        => 10000,
                'thanh_tien'     => 10000,
            ],
            [
                'id_don_hang'    => 0,
                'id_khach_hang'  => 5,
                'id_mon_an'      => 45,
                'id_quan_an'     => 12,
                'so_luong'       => 1,
                'don_gia'        => 30000,
                'thanh_tien'     => 30000,
            ],
            [
                'id_don_hang'    => 0,
                'id_khach_hang'  => 6,
                'id_mon_an'      => 3,
                'id_quan_an'     => 2,
                'so_luong'       => 1,
                'don_gia'        => 17000,
                'thanh_tien'     => 17000,
            ],
            [
                'id_don_hang'    => 0,
                'id_khach_hang'  => 7,
                'id_mon_an'      => 18,
                'id_quan_an'     => 4,
                'so_luong'       => 1,
                'don_gia'        => 50000,
                'thanh_tien'     => 50000,
            ],
            [
                'id_don_hang'    => 0,
                'id_khach_hang'  => 1,
                'id_mon_an'      => 38,
                'id_quan_an'     => 10,
                'so_luong'       => 1,
                'don_gia'        => 25000,
                'thanh_tien'     => 25000,
            ],
            [
                'id_don_hang'    => 0,
                'id_khach_hang'  => 2,
                'id_mon_an'      => 56,
                'id_quan_an'     => 14,
                'so_luong'       => 1,
                'don_gia'        => 25000,
                'thanh_tien'     => 25000,
            ],
            [
                'id_don_hang'    => 0,
                'id_khach_hang'  => 3,
                'id_mon_an'      => 61,
                'id_quan_an'     => 15,
                'so_luong'       => 1,
                'don_gia'        => 20000,
                'thanh_tien'     => 20000,
            ],
            [
                'id_don_hang'    => 0,
                'id_khach_hang'  => 1,
                'id_mon_an'      => 12,
                'id_quan_an'     => 3,
                'so_luong'       => 1,
                'don_gia'        => 25000,
                'thanh_tien'     => 25000,
            ],
            [
                'id_don_hang'    => 0,
                'id_khach_hang'  => 2,
                'id_mon_an'      => 14,
                'id_quan_an'     => 4,
                'so_luong'       => 1,
                'don_gia'        => 30000,
                'thanh_tien'     => 30000,
            ],
            [
                'id_don_hang'    => 0,
                'id_khach_hang'  => 4,
                'id_mon_an'      => 20,
                'id_quan_an'     => 5,
                'so_luong'       => 1,
                'don_gia'        => 30000,
                'thanh_tien'     => 30000,
            ],
            [
                'id_don_hang'    => 0,
                'id_khach_hang'  => 5,
                'id_mon_an'      => 22,
                'id_quan_an'     => 6,
                'so_luong'       => 1,
                'don_gia'        => 40000,
                'thanh_tien'     => 40000,
            ],
            [
                'id_don_hang'    => 0,
                'id_khach_hang'  => 6,
                'id_mon_an'      => 25,
                'id_quan_an'     => 7,
                'so_luong'       => 1,
                'don_gia'        => 40000,
                'thanh_tien'     => 40000,
            ],
            [
                'id_don_hang'    => 0,
                'id_khach_hang'  => 1,
                'id_mon_an'      => 13,
                'id_quan_an'     => 4,
                'so_luong'       => 1,
                'don_gia'        => 30000,
                'thanh_tien'     => 30000,
            ],
            [
                'id_don_hang'    => 0,
                'id_khach_hang'  => 2,
                'id_mon_an'      => 23,
                'id_quan_an'     => 6,
                'so_luong'       => 1,
                'don_gia'        => 40000,
                'thanh_tien'     => 40000,
            ],
            [
                'id_don_hang'    => 0,
                'id_khach_hang'  => 3,
                'id_mon_an'      => 2,
                'id_quan_an'     => 2,
                'so_luong'       => 1,
                'don_gia'        => 20000,
                'thanh_tien'     => 20000,
            ],
            [
                'id_don_hang'    => 0,
                'id_khach_hang'  => 5,
                'id_mon_an'      => 26,
                'id_quan_an'     => 7,
                'so_luong'       => 1,
                'don_gia'        => 40000,
                'thanh_tien'     => 40000,
            ],
            [
                'id_don_hang'    => 0,
                'id_khach_hang'  => 6,
                'id_mon_an'      => 27,
                'id_quan_an'     => 8,
                'so_luong'       => 1,
                'don_gia'        => 30000,
                'thanh_tien'     => 30000,
            ],
            [
                'id_don_hang'    => 0,
                'id_khach_hang'  => 1,
                'id_mon_an'      => 3,
                'id_quan_an'     => 2,
                'so_luong'       => 1,
                'don_gia'        => 17000,
                'thanh_tien'     => 17000,
            ],
            [
                'id_don_hang'    => 0,
                'id_khach_hang'  => 2,
                'id_mon_an'      => 24,
                'id_quan_an'     => 6,
                'so_luong'       => 1,
                'don_gia'        => 40000,
                'thanh_tien'     => 40000,
            ],
            [
                'id_don_hang'    => 0,
                'id_khach_hang'  => 3,
                'id_mon_an'      => 4,
                'id_quan_an'     => 2,
                'so_luong'       => 1,
                'don_gia'        => 25000,
                'thanh_tien'     => 25000,
            ],
            [
                'id_don_hang'    => 0,
                'id_khach_hang'  => 4,
                'id_mon_an'      => 11,
                'id_quan_an'     => 3,
                'so_luong'       => 1,
                'don_gia'        => 25000,
                'thanh_tien'     => 25000,
            ],
            [
                'id_don_hang'    => 0,
                'id_khach_hang'  => 5,
                'id_mon_an'      => 28,
                'id_quan_an'     => 8,
                'so_luong'       => 1,
                'don_gia'        => 30000,
                'thanh_tien'     => 30000,
            ],
            [
                'id_don_hang'    => 0,
                'id_khach_hang'  => 1,
                'id_mon_an'      => 25,
                'id_quan_an'     => 7,
                'so_luong'       => 1,
                'don_gia'        => 40000,
                'thanh_tien'     => 40000,
            ],
            [
                'id_don_hang'    => 0,
                'id_khach_hang'  => 2,
                'id_mon_an'      => 31,
                'id_quan_an'     => 9,
                'so_luong'       => 1,
                'don_gia'        => 10000,
                'thanh_tien'     => 10000,
            ],
            [
                'id_don_hang'    => 0,
                'id_khach_hang'  => 3,
                'id_mon_an'      => 38,
                'id_quan_an'     => 10,
                'so_luong'       => 1,
                'don_gia'        => 25000,
                'thanh_tien'     => 25000,
            ],
            [
                'id_don_hang'    => 0,
                'id_khach_hang'  => 4,
                'id_mon_an'      => 19,
                'id_quan_an'     => 5,
                'so_luong'       => 1,
                'don_gia'        => 30000,
                'thanh_tien'     => 30000,
            ],
            [
                'id_don_hang'    => 0,
                'id_khach_hang'  => 5,
                'id_mon_an'      => 6,
                'id_quan_an'     => 2,
                'so_luong'       => 1,
                'don_gia'        => 20000,
                'thanh_tien'     => 20000,
            ],
        ]);
    }
}
