<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DonHangSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('don_hangs')->delete();
        DB::table('don_hangs')->truncate();
        DB::table('don_hangs')->insert([
            [
                'id'    => 1,
                'ma_don_hang' => 'DH001',
                'id_khach_hang' => 1,
                'id_voucher' => null,
                'id_shipper' => null,
                'id_quan_an' => 2,
                'id_dia_chi_nhan' => 1,
                'ten_nguoi_nhan' => 'Võ Văn Việt',
                'so_dien_thoai' => '0123456780',
                'tien_hang' => 17000,
                'phi_ship' => 10000,
                'tong_tien' => 27000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'ma_don_hang' => 'DH002',
                'id_khach_hang' => 1,
                'id_voucher' => null,
                'id_shipper' => 1,
                'id_quan_an' => 3,
                'id_dia_chi_nhan' => 2,
                'ten_nguoi_nhan' => 'Võ Văn Việt',
                'so_dien_thoai' => '0123456780',
                'tien_hang' => 37000,
                'phi_ship' => 15000,
                'tong_tien' => 52000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'ma_don_hang' => 'DH003',
                'id_khach_hang' => 1,
                'id_voucher' => null,
                'id_shipper' => null,
                'id_quan_an' => 10,
                'id_dia_chi_nhan' => 3,
                'ten_nguoi_nhan' => 'Võ Văn Việt',
                'so_dien_thoai' => '0123456780',
                'tien_hang' => 20000,
                'phi_ship' => 15000,
                'tong_tien' => 25000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 4,
                'ma_don_hang' => 'DH004',
                'id_khach_hang' => 2,
                'id_voucher' => null,
                'id_shipper' => null,
                'id_quan_an' => 6,
                'id_dia_chi_nhan' => 4,
                'ten_nguoi_nhan' => 'Nguyễn Văn A',
                'so_dien_thoai' => '0123456789',
                'tien_hang' => 80000,
                'phi_ship' => 25000,
                'tong_tien' => 105000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 5,
                'ma_don_hang' => 'DH005',
                'id_khach_hang' => 2,
                'id_voucher' => null,
                'id_shipper' => null,
                'id_quan_an' => 14,
                'id_dia_chi_nhan' => 5,
                'ten_nguoi_nhan' => 'Nguyễn Văn A',
                'so_dien_thoai' => '0123456789',
                'tien_hang' => 25000,
                'phi_ship' => 15000,
                'tong_tien' => 40000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 6,
                'ma_don_hang' => 'DH006',
                'id_khach_hang' => 3,
                'id_voucher' => null,
                'id_shipper' => 1,
                'id_quan_an' => 10,
                'id_dia_chi_nhan' => 7,
                'ten_nguoi_nhan' => 'Lê Minh Tuấn',
                'so_dien_thoai' => '0987654321',
                'tien_hang' => 25000,
                'phi_ship' => 15000,
                'tong_tien' => 40000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 7,
                'ma_don_hang' => 'DH007',
                'id_khach_hang' => 4,
                'id_voucher' => null,
                'id_shipper' => null,
                'id_quan_an' => 5,
                'id_dia_chi_nhan' => 10,
                'ten_nguoi_nhan' => 'Trần Thị Hồng Nhung',
                'so_dien_thoai' => '0911223344',
                'tien_hang' => 60000,
                'phi_ship' => 17000,
                'tong_tien' => 77000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 8,
                'ma_don_hang' => 'DH008',
                'id_khach_hang' => 5,
                'id_voucher' => null,
                'id_shipper' => 1,
                'id_quan_an' => 12,
                'id_dia_chi_nhan' => 13,
                'ten_nguoi_nhan' => 'Đặng Quốc Huy',
                'so_dien_thoai' => '0933445566',
                'tien_hang' => 30000,
                'phi_ship' => 17000,
                'tong_tien' => 47000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 9,
                'ma_don_hang' => 'DH009',
                'id_khach_hang' => 6,
                'id_voucher' => null,
                'id_shipper' => null,
                'id_quan_an' => 8,
                'id_dia_chi_nhan' => 17,
                'ten_nguoi_nhan' => 'Phạm Thị Mai',
                'so_dien_thoai' => '0909887766',
                'tien_hang' => 30000,
                'phi_ship' => 15000,
                'tong_tien' => 45000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'    => 10,
                'ma_don_hang' => 'DH010',
                'id_khach_hang' => 7,
                'id_voucher' => null,
                'id_shipper' => 2,
                'id_quan_an' => 4,
                'id_dia_chi_nhan' => 21,
                'ten_nguoi_nhan' => 'Ngô Văn Lâm',
                'so_dien_thoai' => '0966887799',
                'tien_hang' => 50000,
                'phi_ship' => 15000,
                'tong_tien' => 55000,
                'is_thanh_toan' => 0,
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
