<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MonAnSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('mon_ans')->delete();

        DB::table('mon_ans')->truncate();

        DB::table('mon_ans')->insert([
            ['id' => '1', 'ten_mon_an' => 'Cafe Dừa', 'slug_mon_an' => 'cafe-dua', 'gia_ban' => '20000', 'gia_khuyen_mai' => '15000', 'mo_ta' => '', 'id_quan_an' => '2', 'tinh_trang' => '1', 'hinh_anh' => 'https://bonjourcoffee.vn/blog/wp-content/uploads/2019/11/ca-phe-cot-dua.jpg', 'id_danh_muc' => '17'],
            ['id' => '2', 'ten_mon_an' => 'Cafe Máy', 'slug_mon_an' => 'cafe-may', 'gia_ban' => '20000', 'gia_khuyen_mai' => '15000', 'mo_ta' => '', 'id_quan_an' => '2', 'tinh_trang' => '1', 'hinh_anh' => 'https://artcoffee.vn/wp-content/uploads/ca-phe-pha-may-1024x679-3.jpg', 'id_danh_muc' => '17'],
            ['id' => '3', 'ten_mon_an' => 'Cafe Sữa', 'slug_mon_an' => 'cafe-sua', 'gia_ban' => '17000', 'gia_khuyen_mai' => '12000', 'mo_ta' => '', 'id_quan_an' => '2', 'tinh_trang' => '1', 'hinh_anh' => 'https://artcoffee.vn/wp-content/uploads/ca-phe-pha-may-1024x679-3.jpg', 'id_danh_muc' => '17'],
            ['id' => '4', 'ten_mon_an' => 'Cafe Muối', 'slug_mon_an' => 'cafe-muoi', 'gia_ban' => '25000', 'gia_khuyen_mai' => '20000', 'mo_ta' => '', 'id_quan_an' => '2', 'tinh_trang' => '1', 'hinh_anh' => 'https://kinhte.congthuong.vn/stores/news_dataimages/2023/092023/30/15/in_article/ca-phe-muoi-220230930151322.png?rt=20230930151323', 'id_danh_muc' => '17'],
            ['id' => '5', 'ten_mon_an' => 'Nước Chanh', 'slug_mon_an' => 'nuoc-chanh', 'gia_ban' => '15000', 'gia_khuyen_mai' => '10000', 'mo_ta' => '', 'id_quan_an' => '2', 'tinh_trang' => '1', 'hinh_anh' => 'https://www.huongnghiepaau.com/wp-content/uploads/2022/01/nuoc-chanh-loi-ich-cho-suc-khoe.jpg', 'id_danh_muc' => '19'],
            ['id' => '6', 'ten_mon_an' => 'Nước Cam Ép', 'slug_mon_an' => 'nuoc-cam', 'gia_ban' => '20000', 'gia_khuyen_mai' => '15000', 'mo_ta' => '', 'id_quan_an' => '2', 'tinh_trang' => '1', 'hinh_anh' => 'https://suckhoedoisong.qltns.mediacdn.vn/324455921873985536/2023/11/7/uong-nuoc-cam-16993504421751885406385.jpg', 'id_danh_muc' => '19'],
            ['id' => '7', 'ten_mon_an' => 'Nước Ép Cà Rốt', 'slug_mon_an' => 'nuoc-ep-ca-rot', 'gia_ban' => '20000', 'gia_khuyen_mai' => '15000', 'mo_ta' => '', 'id_quan_an' => '2', 'tinh_trang' => '1', 'hinh_anh' => 'https://hutiuthanhdat.vn/timthumb.php?src=data/Product/nuoc-ep-ca-rot.jpg&h=600&w=600&zc=1', 'id_danh_muc' => '19'],
            ['id' => '8', 'ten_mon_an' => 'Nước Ép Thơm', 'slug_mon_an' => 'nuoc-ep-thom', 'gia_ban' => '20000', 'gia_khuyen_mai' => '15000', 'mo_ta' => '', 'id_quan_an' => '2', 'tinh_trang' => '1', 'hinh_anh' => 'https://win-rd.com/wp-content/uploads/2021/06/6-cong-dung-cua-nuoc-ep-dua-cach-lam-va-bao-quan-nuoc-ep-dua-0-1200x676-1.jpg', 'id_danh_muc' => '19'],
            ['id' => '9', 'ten_mon_an' => 'Lục Trà Chanh ', 'slug_mon_an' => 'luc-tra-chanh', 'gia_ban' => '25000', 'gia_khuyen_mai' => '20000', 'mo_ta' => '', 'id_quan_an' => '3', 'tinh_trang' => '1', 'hinh_anh' => 'https://nguyenlieuphachehanoi.com/wp-content/uploads/2019/05/cong-thuc-sieu-pham-tra-chanh.jpg', 'id_danh_muc' => '18'],
            ['id' => '10', 'ten_mon_an' => 'Lục Trà Xoài', 'slug_mon_an' => 'luc-tra-xoai', 'gia_ban' => '25000', 'gia_khuyen_mai' => '20000', 'mo_ta' => '', 'id_quan_an' => '3', 'tinh_trang' => '1', 'hinh_anh' => 'https://mevacon.giaoduc.edu.vn/wp-content/uploads/2022/06/cach-lam-tra-xoai.jpeg', 'id_danh_muc' => '18'],
            ['id' => '11', 'ten_mon_an' => 'Matcha Đá Xay', 'slug_mon_an' => 'matcha-da-xay', 'gia_ban' => '25000', 'gia_khuyen_mai' => '20000', 'mo_ta' => '', 'id_quan_an' => '3', 'tinh_trang' => '1', 'hinh_anh' => 'https://vhealthcoffee.com.vn/uploads/MATCHA%20%C4%90%C3%81%20XAY.gif', 'id_danh_muc' => '16'],
            ['id' => '12', 'ten_mon_an' => 'Socola Đá Xay', 'slug_mon_an' => 'socola-da-xay', 'gia_ban' => '25000', 'gia_khuyen_mai' => '20000', 'mo_ta' => '', 'id_quan_an' => '3', 'tinh_trang' => '1', 'hinh_anh' => 'https://lamaca.vn/wp-content/uploads/2021/08/cafe-chocolate-da-xay.jpg', 'id_danh_muc' => '16'],
            ['id' => '13', 'ten_mon_an' => 'Phin Sữa Đá', 'slug_mon_an' => 'phin-sua-da', 'gia_ban' => '30000', 'gia_khuyen_mai' => '25000', 'mo_ta' => '', 'id_quan_an' => '4', 'tinh_trang' => '1', 'hinh_anh' => 'https://themiquanghouse.com/upload/product/27491897316517219318329225165003444167276803n-2837.jpg', 'id_danh_muc' => '17'],
            ['id' => '14', 'ten_mon_an' => 'Phin Đen Đá', 'slug_mon_an' => 'phin-den-da', 'gia_ban' => '30000', 'gia_khuyen_mai' => '25000', 'mo_ta' => '', 'id_quan_an' => '4', 'tinh_trang' => '1', 'hinh_anh' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZtUmYOx21DZHd4oT24h8uFU84EQpm1Ep7IcVni9aFIA&s', 'id_danh_muc' => '17'],
            ['id' => '15', 'ten_mon_an' => 'Bạc Xỉu', 'slug_mon_an' => 'bac-xiu', 'gia_ban' => '30000', 'gia_khuyen_mai' => '25000', 'mo_ta' => '', 'id_quan_an' => '4', 'tinh_trang' => '1', 'hinh_anh' => 'https://robicacoffee.com/wp-content/uploads/2021/09/bac-xiu-da.jpg', 'id_danh_muc' => '17'],
            ['id' => '16', 'ten_mon_an' => 'Freeze Trà Xanh', 'slug_mon_an' => 'freeze-tra-xanh', 'gia_ban' => '50000', 'gia_khuyen_mai' => '45000', 'mo_ta' => '', 'id_quan_an' => '4', 'tinh_trang' => '1', 'hinh_anh' => 'https://dvpmarket.com/resources/uploads/images/2018/07/Freeze-tra-xanh-tuoi-mat-thom-ngon-1.jpg', 'id_danh_muc' => '18'],
            ['id' => '17', 'ten_mon_an' => 'Freeze Socola', 'slug_mon_an' => 'freeze-socola', 'gia_ban' => '50000', 'gia_khuyen_mai' => '45000', 'mo_ta' => '', 'id_quan_an' => '4', 'tinh_trang' => '1', 'hinh_anh' => 'https://recipes.net/wp-content/uploads/portal_files/recipes_net_posts/2021-06/freeze-easy-chocolate-shake-recipe.png', 'id_danh_muc' => '18'],
            ['id' => '18', 'ten_mon_an' => 'Classic Phin Freeze', 'slug_mon_an' => 'classic-phin-freeze', 'gia_ban' => '50000', 'gia_khuyen_mai' => '45000', 'mo_ta' => '', 'id_quan_an' => '4', 'tinh_trang' => '1', 'hinh_anh' => 'https://www.highlandscoffee.com.vn/vnt_upload/product/06_2023/HLC_New_logo_5.1_Products__CLASSIC_FREEZE_PHINDI.jpg', 'id_danh_muc' => '18'],
            ['id' => '19', 'ten_mon_an' => 'Cơm Tấm Sườn', 'slug_mon_an' => 'com-tam-suon', 'gia_ban' => '30000', 'gia_khuyen_mai' => '25000', 'mo_ta' => '', 'id_quan_an' => '5', 'tinh_trang' => '1', 'hinh_anh' => 'https://lamsonfood.com/wp-content/uploads/2022/02/com-tam-duoc-nhieu-nguoi-yeu-thich.jpg', 'id_danh_muc' => '22'],
            ['id' => '20', 'ten_mon_an' => 'Cơm Tấm Sườn Nướng', 'slug_mon_an' => 'com-tam-suon-nuong', 'gia_ban' => '30000', 'gia_khuyen_mai' => '25000', 'mo_ta' => '', 'id_quan_an' => '5', 'tinh_trang' => '1', 'hinh_anh' => 'https://cdn.tgdd.vn/Files/2021/08/09/1373996/tu-lam-com-tam-suon-trung-don-gian-thom-ngon-nhu-ngoai-hang-202201071248422991.jpg', 'id_danh_muc' => '22'],
            ['id' => '21', 'ten_mon_an' => 'Cơm Gà Xé', 'slug_mon_an' => 'com-ga-xe', 'gia_ban' => '30000', 'gia_khuyen_mai' => '25000', 'mo_ta' => '', 'id_quan_an' => '5', 'tinh_trang' => '1', 'hinh_anh' => 'https://phugiafood.com/wp-content/uploads/2021/11/Com-ga-xe-phay-1-1024x768.jpg', 'id_danh_muc' => '20'],
            ['id' => '22', 'ten_mon_an' => 'Cơm Chiên Dương Châu', 'slug_mon_an' => 'com-chien-duong-chau', 'gia_ban' => '40000', 'gia_khuyen_mai' => '35000', 'mo_ta' => '', 'id_quan_an' => '6', 'tinh_trang' => '1', 'hinh_anh' => 'https://i.ytimg.com/vi/ZbSbc9Z8K6E/maxresdefault.jpg', 'id_danh_muc' => '23'],
            ['id' => '23', 'ten_mon_an' => 'Cơm Đùi Gà Quay', 'slug_mon_an' => 'com-dui-ga-quay', 'gia_ban' => '40000', 'gia_khuyen_mai' => '35000', 'mo_ta' => '', 'id_quan_an' => '6', 'tinh_trang' => '1', 'hinh_anh' => 'https://29foods.com/media/news/583_com_ga_quay.jpg', 'id_danh_muc' => '23'],
            ['id' => '24', 'ten_mon_an' => 'Cơm Cánh Gà Quay', 'slug_mon_an' => 'com-canh-ga-quay', 'gia_ban' => '40000', 'gia_khuyen_mai' => '35000', 'mo_ta' => '', 'id_quan_an' => '6', 'tinh_trang' => '1', 'hinh_anh' => 'https://29foods.com/media/news/1212_com-ga-quay1.jpg', 'id_danh_muc' => '23'],
            ['id' => '25', 'ten_mon_an' => 'Cơm Chiên Trứng', 'slug_mon_an' => 'com-chien-trung', 'gia_ban' => '40000', 'gia_khuyen_mai' => '35000', 'mo_ta' => '', 'id_quan_an' => '7', 'tinh_trang' => '1', 'hinh_anh' => 'https://cdn.tgdd.vn/Files/2019/06/05/1171265/cach-lam-com-chien-trung-hat-com-toi-khong-bi-nhao-202203031523399671.jpg', 'id_danh_muc' => '23'],
            ['id' => '26', 'ten_mon_an' => 'Cơm Chiên Heo Quay', 'slug_mon_an' => 'com-chien-heo-quay', 'gia_ban' => '40000', 'gia_khuyen_mai' => '35000', 'mo_ta' => '', 'id_quan_an' => '7', 'tinh_trang' => '1', 'hinh_anh' => 'https://img-global.cpcdn.com/recipes/1f3479b6cd02e393/680x482cq70/c%C6%A1m-rang-th%E1%BB%8Bt-heo-quay-lowcarb-recipe-main-photo.jpg', 'id_danh_muc' => '23'],
            ['id' => '27', 'ten_mon_an' => 'Cơm Cá Kho', 'slug_mon_an' => 'com-ca-kho', 'gia_ban' => '30000', 'gia_khuyen_mai' => '25000', 'mo_ta' => '', 'id_quan_an' => '8', 'tinh_trang' => '1', 'hinh_anh' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfwb1ykZI87IDRIJC503E0k4Y2YcbVYHsyxqavxOb57g&s', 'id_danh_muc' => '20'],
            ['id' => '28', 'ten_mon_an' => 'Cơm Sườn Non', 'slug_mon_an' => 'com-suon-non', 'gia_ban' => '30000', 'gia_khuyen_mai' => '25000', 'mo_ta' => '', 'id_quan_an' => '8', 'tinh_trang' => '1', 'hinh_anh' => 'https://comtamthuankieu.com.vn/wp-content/uploads/2020/12/IMG_0054-scaled.jpg', 'id_danh_muc' => '20'],
            ['id' => '29', 'ten_mon_an' => 'Cơm Tôm Rim', 'slug_mon_an' => 'com-tom-rim', 'gia_ban' => '30000', 'gia_khuyen_mai' => '25000', 'mo_ta' => '', 'id_quan_an' => '8', 'tinh_trang' => '1', 'hinh_anh' => 'https://product.hstatic.net/1000245833/product/c_m_t_m_rim_master.jpg', 'id_danh_muc' => '20'],
            ['id' => '30', 'ten_mon_an' => 'Xôi Chiên Thịt Băm', 'slug_mon_an' => 'xoi-chien-thit-bam', 'gia_ban' => '10000', 'gia_khuyen_mai' => '5000', 'mo_ta' => '', 'id_quan_an' => '9', 'tinh_trang' => '1', 'hinh_anh' => 'https://cdn.tgdd.vn/Files/2014/10/09/572276/bi-quyet-lam-xoi-chien-cang-an-cang-ghien--7.jpg', 'id_danh_muc' => '21'],
            ['id' => '31', 'ten_mon_an' => 'Xôi Chiên Thịt Xíu', 'slug_mon_an' => 'xoi-chien-thit-xiu', 'gia_ban' => '10000', 'gia_khuyen_mai' => '5000', 'mo_ta' => '', 'id_quan_an' => '9', 'tinh_trang' => '1', 'hinh_anh' => 'https://cdn.mediamart.vn/images/news/mach-bn-cach-lam-xoi-xa-xiu-cc-ngon-ch-vi-ni-chien-khong-du_3bb08258.jpg', 'id_danh_muc' => '21'],
            ['id' => '32', 'ten_mon_an' => 'Xôi Chiên Gà Xé Cay', 'slug_mon_an' => 'xoi-chien-ga-xe-cay', 'gia_ban' => '10000', 'gia_khuyen_mai' => '5000', 'mo_ta' => '', 'id_quan_an' => '9', 'tinh_trang' => '1', 'hinh_anh' => 'https://daubepgiadinh.vn/wp-content/uploads/2018/05/hinh-xoi-ga-xe-600x400.jpg', 'id_danh_muc' => '21'],
            ['id' => '33', 'ten_mon_an' => 'Xôi Chiên Chà Bông', 'slug_mon_an' => 'xoi-chien-cha-bong', 'gia_ban' => '10000', 'gia_khuyen_mai' => '5000', 'mo_ta' => '', 'id_quan_an' => '9', 'tinh_trang' => '1', 'hinh_anh' => 'https://cdn.tgdd.vn/2021/08/CookRecipe/Avatar/xoi-chien-cha-bong-mo-hanh-thumbnail-1.jpg', 'id_danh_muc' => '21'],
            ['id' => '34', 'ten_mon_an' => 'Cá Viên Chiên', 'slug_mon_an' => 'ca-vien-chien', 'gia_ban' => '10000', 'gia_khuyen_mai' => '5000', 'mo_ta' => '', 'id_quan_an' => '9', 'tinh_trang' => '1', 'hinh_anh' => 'https://www.cet.edu.vn/wp-content/uploads/2018/04/ca-vien-chien.jpg', 'id_danh_muc' => '28'],
            ['id' => '35', 'ten_mon_an' => 'Tôm Viên Chiên', 'slug_mon_an' => 'tom-vien-chien', 'gia_ban' => '10000', 'gia_khuyen_mai' => '5000', 'mo_ta' => '', 'id_quan_an' => '9', 'tinh_trang' => '1', 'hinh_anh' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTOLlJNN0JFT8BW_MWp0Q5qtHeTLXxTJDPLieklxW2mg&s', 'id_danh_muc' => '28'],
            ['id' => '36', 'ten_mon_an' => 'Bò Viên Chiên', 'slug_mon_an' => 'bo-vien-chien', 'gia_ban' => '10000', 'gia_khuyen_mai' => '5000', 'mo_ta' => '', 'id_quan_an' => '9', 'tinh_trang' => '1', 'hinh_anh' => 'https://cdn.tgdd.vn/Files/2021/08/21/1376755/cach-lam-bo-vien-chay-thom-ngon-chuan-vi-an-cung-bun-pho-deu-ngon-202201040958095687.jpg', 'id_danh_muc' => '28'],
            ['id' => '37', 'ten_mon_an' => 'Xúc Xích Chiên', 'slug_mon_an' => 'xuc-xich-chien', 'gia_ban' => '10000', 'gia_khuyen_mai' => '5000', 'mo_ta' => '', 'id_quan_an' => '9', 'tinh_trang' => '1', 'hinh_anh' => 'https://food.ibin.vn/images/data/product/do-an-nhe/xuc-xich-chien.jpg', 'id_danh_muc' => '28'],
            ['id' => '38', 'ten_mon_an' => 'Bún Thịt Nướng ', 'slug_mon_an' => 'bun-thit-nuong', 'gia_ban' => '25000', 'gia_khuyen_mai' => '20000', 'mo_ta' => '', 'id_quan_an' => '10', 'tinh_trang' => '1', 'hinh_anh' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIQAT_x0LrhDZzz23U7lUfRVKqP7pYOwYOZ2IcWIgZ-g&s', 'id_danh_muc' => '8'],
            ['id' => '39', 'ten_mon_an' => 'Bún Thập Cẩm', 'slug_mon_an' => 'bun-thap-cam', 'gia_ban' => '25000', 'gia_khuyen_mai' => '20000', 'mo_ta' => '', 'id_quan_an' => '10', 'tinh_trang' => '1', 'hinh_anh' => 'https://mms.img.susercontent.com/vn-11134513-7r98o-lsvfjjza4pll6e@resize_ss1242x600!@crop_w1242_h600_cT', 'id_danh_muc' => '8'],
            ['id' => '40', 'ten_mon_an' => 'Bún Mắm', 'slug_mon_an' => 'bun-mam', 'gia_ban' => '25000', 'gia_khuyen_mai' => '20000', 'mo_ta' => '', 'id_quan_an' => '10', 'tinh_trang' => '1', 'hinh_anh' => 'https://cdn.vntrip.vn/cam-nang/wp-content/uploads/2016/12/huong-vi-thom-ngon-kho-quen-cua-mon-bun-mam-nem-da-nang-953-5.jpg', 'id_danh_muc' => '8'],
            ['id' => '41', 'ten_mon_an' => 'Nước Ép Cà Rốt', 'slug_mon_an' => 'nuoc-ep-ca-rot', 'gia_ban' => '20000', 'gia_khuyen_mai' => '20000', 'mo_ta' => '', 'id_quan_an' => '11', 'tinh_trang' => '1', 'hinh_anh' => 'https://matika.vn/wp-content/uploads/2022/09/cach-lam-nuoc-ep-ca-rot-ngon-nd.jpg', 'id_danh_muc' => '19'],
            ['id' => '42', 'ten_mon_an' => 'Nước Dừa', 'slug_mon_an' => 'nuoc-dua', 'gia_ban' => '20000', 'gia_khuyen_mai' => '15000', 'mo_ta' => '', 'id_quan_an' => '11', 'tinh_trang' => '1', 'hinh_anh' => 'https://www.vinmec.com/s3-images/20200513_094457_911488_loi-ich-cua-nuoc-dua-.max-800x800.jpg', 'id_danh_muc' => '19'],
            ['id' => '43', 'ten_mon_an' => 'Nước Ép Dưa Hấu', 'slug_mon_an' => 'nuoc-ep-dua-hau', 'gia_ban' => '20000', 'gia_khuyen_mai' => '15000', 'mo_ta' => '', 'id_quan_an' => '11', 'tinh_trang' => '1', 'hinh_anh' => 'https://cdn.tgdd.vn/Files/2020/10/23/1301299/5-cach-lam-nuoc-ep-dua-hau-cuc-ngon-don-gian-tai-nha-202010231109233490.jpg', 'id_danh_muc' => '19'],
            ['id' => '44', 'ten_mon_an' => 'Nước Mía', 'slug_mon_an' => 'nuoc-mia', 'gia_ban' => '20000', 'gia_khuyen_mai' => '15000', 'mo_ta' => '', 'id_quan_an' => '11', 'tinh_trang' => '1', 'hinh_anh' => 'https://cdn.nhathuoclongchau.com.vn/unsafe/800x0/https://cms-prod.s3-sgn09.fptcloud.com/nuoc_mia_co_tac_dung_gi_doi_voi_suc_khoe_1_3faa508da1.jpg', 'id_danh_muc' => '19'],
            ['id' => '45', 'ten_mon_an' => 'Trà Sữa Trân Châu Đường Đen', 'slug_mon_an' => 'tra-sua-tran-chau-duong-den', 'gia_ban' => '30000', 'gia_khuyen_mai' => '25000', 'mo_ta' => '', 'id_quan_an' => '12', 'tinh_trang' => '1', 'hinh_anh' => 'https://cdn.tgdd.vn/Files/2022/01/21/1412109/huong-dan-cach-lam-tra-sua-tran-chau-duong-den-202201211537260116.jpg', 'id_danh_muc' => '16'],
            ['id' => '46', 'ten_mon_an' => 'Trà Sữa Truyền Thống', 'slug_mon_an' => 'tra-sua-truyen-thong', 'gia_ban' => '30000', 'gia_khuyen_mai' => '25000', 'mo_ta' => '', 'id_quan_an' => '12', 'tinh_trang' => '1', 'hinh_anh' => 'https://cdn.tgdd.vn/Files/2021/08/10/1374160/hoc-2-cach-pha-tra-sua-truyen-thong-thom-ngon-chuan-vi-ai-cung-me-202203031716377004.jpg', 'id_danh_muc' => '16'],
            ['id' => '47', 'ten_mon_an' => 'Trà Sữa Bạc Hà', 'slug_mon_an' => 'tra-sua-bac-ha', 'gia_ban' => '30000', 'gia_khuyen_mai' => '25000', 'mo_ta' => '', 'id_quan_an' => '12', 'tinh_trang' => '1', 'hinh_anh' => 'https://cdn.nguyenkimmall.com/images/detailed/747/6-tra-sua-bac-ha.jpg.jpg', 'id_danh_muc' => '16'],
            ['id' => '48', 'ten_mon_an' => 'Trà Sữa Khoai Môn', 'slug_mon_an' => 'tra-sua-khoai-mon', 'gia_ban' => '30000', 'gia_khuyen_mai' => '25000', 'mo_ta' => '', 'id_quan_an' => '12', 'tinh_trang' => '1', 'hinh_anh' => 'https://cdn.tgdd.vn/Files/2021/11/04/1395665/cach-lam-tra-sua-khoai-mon-thom-ngon-chuan-vi-202111041038558095.jpg', 'id_danh_muc' => '16'],
            ['id' => '49', 'ten_mon_an' => 'Trà Sữa Sương Sáo', 'slug_mon_an' => 'tra-sua-suong-sao', 'gia_ban' => '30000', 'gia_khuyen_mai' => '25000', 'mo_ta' => '', 'id_quan_an' => '12', 'tinh_trang' => '1', 'hinh_anh' => 'https://cdn.tgdd.vn/2021/09/CookRecipe/Avatar/tra-sua-suong-sao-bang-bot-beo-thumbnail-1.jpg', 'id_danh_muc' => '16'],
            ['id' => '50', 'ten_mon_an' => 'Trà Chanh Nhãn', 'slug_mon_an' => 'tra-chanh-nhan', 'gia_ban' => '30000', 'gia_khuyen_mai' => '25000', 'mo_ta' => '', 'id_quan_an' => '12', 'tinh_trang' => '1', 'hinh_anh' => 'https://longnhanbamai.com/wp-content/uploads/2018/08/Cach-pha-tra-nhan-ngon.jpg', 'id_danh_muc' => '18'],
            ['id' => '51', 'ten_mon_an' => 'Trà Chanh Bạc Hà', 'slug_mon_an' => 'tra-chanh-bac-ha', 'gia_ban' => '30000', 'gia_khuyen_mai' => '25000', 'mo_ta' => '', 'id_quan_an' => '12', 'tinh_trang' => '1', 'hinh_anh' => 'https://assets.unileversolutions.com/v1/1188476.jpg', 'id_danh_muc' => '18'],
            ['id' => '52', 'ten_mon_an' => 'Trà Chanh Gừng Sả', 'slug_mon_an' => 'tra-chanh-gung-xa', 'gia_ban' => '30000', 'gia_khuyen_mai' => '25000', 'mo_ta' => '', 'id_quan_an' => '12', 'tinh_trang' => '1', 'hinh_anh' => 'https://images.baodantoc.vn/uploads/2020/Th%C3%A1ng%202/Ng%C3%A0y%2017/tra-sa-e1571990437260.jpg', 'id_danh_muc' => '18'],
            ['id' => '53', 'ten_mon_an' => 'Cơm Chay', 'slug_mon_an' => 'com-chay', 'gia_ban' => '20000', 'gia_khuyen_mai' => '15000', 'mo_ta' => '', 'id_quan_an' => '13', 'tinh_trang' => '1', 'hinh_anh' => 'https://shipdoandemff.com/wp-content/uploads/2017/06/C%C6%A1m-chay-ShipdoandemFF.jpg', 'id_danh_muc' => '20'],
            ['id' => '54', 'ten_mon_an' => 'Bánh Canh Chay', 'slug_mon_an' => 'banh-canh-chay', 'gia_ban' => '20000', 'gia_khuyen_mai' => '15000', 'mo_ta' => '', 'id_quan_an' => '13', 'tinh_trang' => '1', 'hinh_anh' => 'https://cdn.tgdd.vn/2020/11/CookRecipe/GalleryStep/thanh-pham-622.jpg', 'id_danh_muc' => '2'],
            ['id' => '55', 'ten_mon_an' => 'Mì Quảng Chay', 'slug_mon_an' => 'mi-quang-chay', 'gia_ban' => '20000', 'gia_khuyen_mai' => '15000', 'mo_ta' => '', 'id_quan_an' => '13', 'tinh_trang' => '1', 'hinh_anh' => 'https://beptruong.edu.vn/wp-content/uploads/2022/10/mi-quang-chay-voi-vi-thanh-dam.jpg', 'id_danh_muc' => '47'],
            ['id' => '56', 'ten_mon_an' => 'Cà Ri Chay', 'slug_mon_an' => 'ca-ri-chay', 'gia_ban' => '25000', 'gia_khuyen_mai' => '20000', 'mo_ta' => '', 'id_quan_an' => '14', 'tinh_trang' => '1', 'hinh_anh' => 'https://cdn.tgdd.vn/Files/2020/07/10/1269276/cach-nau-ca-ri-chay-thom-ngon-hap-dan-don-gian-tai-nha-202206041935524617.jpg', 'id_danh_muc' => '10'],
            ['id' => '57', 'ten_mon_an' => 'Bánh Kem', 'slug_mon_an' => 'banh-kem', 'gia_ban' => '150000', 'gia_khuyen_mai' => '145000', 'mo_ta' => '', 'id_quan_an' => '15', 'tinh_trang' => '1', 'hinh_anh' => 'https://www.savor.vn/static/a08f8f9a55849d6bd7220ff6ab891c00/28af4/banh-kem-sua-chua-viet-quat.png', 'id_danh_muc' => '31'],
            ['id' => '58', 'ten_mon_an' => 'Bánh Su Kem', 'slug_mon_an' => 'banh-su-kem', 'gia_ban' => '30000', 'gia_khuyen_mai' => '25000', 'mo_ta' => '', 'id_quan_an' => '15', 'tinh_trang' => '1', 'hinh_anh' => 'https://cdn.tgdd.vn/2021/06/CookRecipe/Avatar/banh-su-kem-thumbnail.jpg', 'id_danh_muc' => '31'],
            ['id' => '59', 'ten_mon_an' => 'Cafe Sữa', 'slug_mon_an' => 'cafe-sua', 'gia_ban' => '12000', 'gia_khuyen_mai' => '7000', 'mo_ta' => '', 'id_quan_an' => '15', 'tinh_trang' => '1', 'hinh_anh' => 'https://oola.vn/wp-content/uploads/2023/03/14.-Ca-phe-nau.png', 'id_danh_muc' => '17'],
            ['id' => '60', 'ten_mon_an' => 'Đen Đá', 'slug_mon_an' => 'den-da', 'gia_ban' => '15000', 'gia_khuyen_mai' => '10000', 'mo_ta' => '', 'id_quan_an' => '15', 'tinh_trang' => '1', 'hinh_anh' => 'https://product.hstatic.net/1000075078/product/1639377797_ca-phe-den-da_6f4766ec0f8b4e929a8d916ae3c13254.jpg', 'id_danh_muc' => '17'],
            ['id' => '61', 'ten_mon_an' => 'Bánh Mì Heo Quay', 'slug_mon_an' => 'banh-mi-heo-quay', 'gia_ban' => '20000', 'gia_khuyen_mai' => '15000', 'mo_ta' => '', 'id_quan_an' => '15', 'tinh_trang' => '1', 'hinh_anh' => 'https://cdn.tgdd.vn/Files/2021/09/06/1380700/cach-lam-banh-mi-heo-quay-thom-ngon-cho-bua-sang-dinh-duong-202201041047079624.jpg', 'id_danh_muc' => '6'],
            ['id' => '62', 'ten_mon_an' => 'Bánh Mì Ốp La', 'slug_mon_an' => 'banh-mi-op-la', 'gia_ban' => '20000', 'gia_khuyen_mai' => '15000', 'mo_ta' => '', 'id_quan_an' => '15', 'tinh_trang' => '1', 'hinh_anh' => 'https://hstatic.net/759/1000071759/1/2016/2-22/banh-mi-op-la_master.jpg', 'id_danh_muc' => '6'],
            ['id' => '63', 'ten_mon_an' => 'Bánh Mì Chảo', 'slug_mon_an' => 'banh-mi-chao', 'gia_ban' => '20000', 'gia_khuyen_mai' => '15000', 'mo_ta' => '', 'id_quan_an' => '15', 'tinh_trang' => '1', 'hinh_anh' => 'https://i-giadinh.vnecdn.net/2023/11/03/Buoc-8-Thanh-pham-1-8-2421-1698986152.jpg', 'id_danh_muc' => '6'],
            ['id' => '64', 'ten_mon_an' => 'Nước Dừa', 'slug_mon_an' => 'nuoc-dua', 'gia_ban' => '20000', 'gia_khuyen_mai' => '15000', 'mo_ta' => '', 'id_quan_an' => '16', 'tinh_trang' => '1', 'hinh_anh' => 'https://www.vinmec.com/s3-images/20200513_094457_911488_loi-ich-cua-nuoc-dua-.max-800x800.jpg', 'id_danh_muc' => '19'],
            ['id' => '65', 'ten_mon_an' => 'Nước Dừa Trân châu', 'slug_mon_an' => 'nuoc-dua-tran-chau', 'gia_ban' => '20000', 'gia_khuyen_mai' => '15000', 'mo_ta' => '', 'id_quan_an' => '16', 'tinh_trang' => '1', 'hinh_anh' => 'https://cdn.tgdd.vn/2021/05/CookRecipe/Avatar/nuoc-dua-tran-chau-dua-thumbnail-1.jpg', 'id_danh_muc' => '19'],
            ['id' => '66', 'ten_mon_an' => 'Dừa Kem Sữa', 'slug_mon_an' => 'dua-kem-sua', 'gia_ban' => '20000', 'gia_khuyen_mai' => '15000', 'mo_ta' => '', 'id_quan_an' => '16', 'tinh_trang' => '1', 'hinh_anh' => 'https://cdn.tgdd.vn/Files/2020/03/25/1244397/cach-lam-kem-dua-thom-ngon-tai-nha-bang-may-xay-sinh-to-202003251607205717.jpg', 'id_danh_muc' => '33'],
            ['id' => '67', 'ten_mon_an' => 'Cacao nóng', 'slug_mon_an' => 'cacao-nong', 'gia_ban' => '20000', 'gia_khuyen_mai' => '15000', 'mo_ta' => '', 'id_quan_an' => '16', 'tinh_trang' => '1', 'hinh_anh' => 'https://vietblend.vn/wp-content/uploads/2016/10/0a99b4cc1da4fbfaa2b5.jpg', 'id_danh_muc' => '13'],
            ['id' => '68', 'ten_mon_an' => 'Cacao đá', 'slug_mon_an' => 'cacao-da', 'gia_ban' => '20000', 'gia_khuyen_mai' => '15000', 'mo_ta' => '', 'id_quan_an' => '16', 'tinh_trang' => '1', 'hinh_anh' => 'https://cdn.tgdd.vn/2021/11/CookRecipe/Avatar/ca-cao-da-thumbnail.png', 'id_danh_muc' => '13'],
            ['id' => '69', 'ten_mon_an' => 'Cacao kem trứng', 'slug_mon_an' => 'cacao-kem-trung', 'gia_ban' => '20000', 'gia_khuyen_mai' => '15000', 'mo_ta' => '', 'id_quan_an' => '16', 'tinh_trang' => '1', 'hinh_anh' => 'https://cdn.tgdd.vn/2021/10/CookRecipe/Avatar/cacao-trung-thumbnail.jpg', 'id_danh_muc' => '13'],
            ['id' => '70', 'ten_mon_an' => 'Chè Thái ', 'slug_mon_an' => 'che-thai', 'gia_ban' => '20000', 'gia_khuyen_mai' => '15000', 'mo_ta' => '', 'id_quan_an' => '17', 'tinh_trang' => '1', 'hinh_anh' => 'https://cdn.tgdd.vn/Files/2021/09/08/1381072/cach-lam-che-thai-sau-rieng-thom-ngon-an-la-ghien-202109081353585993.jpg', 'id_danh_muc' => '32'],
            ['id' => '71', 'ten_mon_an' => 'Chè Thái Sầu', 'slug_mon_an' => 'che-thai-sau', 'gia_ban' => '20000', 'gia_khuyen_mai' => '15000', 'mo_ta' => '', 'id_quan_an' => '17', 'tinh_trang' => '1', 'hinh_anh' => 'https://beptruong.edu.vn/wp-content/uploads/2018/06/mon-che-thai-sau-rieng.jpg', 'id_danh_muc' => '32'],
            ['id' => '72', 'ten_mon_an' => 'Chè Bưởi', 'slug_mon_an' => 'che-buoi', 'gia_ban' => '20000', 'gia_khuyen_mai' => '15000', 'mo_ta' => '', 'id_quan_an' => '17', 'tinh_trang' => '1', 'hinh_anh' => 'https://cdn.tgdd.vn/Files/2022/11/20/1488962/cach-nau-che-buoi-sai-gon-thom-sanh-dac-gion-ngon-tai-nha-202211210039464329.jpg', 'id_danh_muc' => '32'],
            ['id' => '73', 'ten_mon_an' => 'Dừa Dầm', 'slug_mon_an' => 'dua-dam', 'gia_ban' => '20000', 'gia_khuyen_mai' => '15000', 'mo_ta' => '', 'id_quan_an' => '17', 'tinh_trang' => '1', 'hinh_anh' => 'https://cdn.tgdd.vn/Files/2021/12/24/1406445/cach-lam-che-dua-dam-ngon-chuan-vi-hai-phong-tai-nha-202112240108007211.jpg', 'id_danh_muc' => '32'],
            ['id' => '74', 'ten_mon_an' => 'Dừa Sữa', 'slug_mon_an' => 'dua-sua', 'gia_ban' => '20000', 'gia_khuyen_mai' => '15000', 'mo_ta' => '', 'id_quan_an' => '17', 'tinh_trang' => '1', 'hinh_anh' => 'https://media.vneconomy.vn/images/upload/2021/04/21/sua-dua-15568650864101847268277.jpg', 'id_danh_muc' => '15'],
            ['id' => '75', 'ten_mon_an' => 'Sườn Bì Chả', 'slug_mon_an' => 'suon-bi-cha', 'gia_ban' => '30000', 'gia_khuyen_mai' => '25000', 'mo_ta' => '', 'id_quan_an' => '18', 'tinh_trang' => '1', 'hinh_anh' => 'https://comtamthuankieu.com.vn/wp-content/uploads/2020/12/IMG_0081-scaled.jpg', 'id_danh_muc' => '22'],
            ['id' => '76', 'ten_mon_an' => 'Sườn Bì ', 'slug_mon_an' => 'suon-bi', 'gia_ban' => '30000', 'gia_khuyen_mai' => '25000', 'mo_ta' => '', 'id_quan_an' => '18', 'tinh_trang' => '1', 'hinh_anh' => 'https://cdn.tgdd.vn/Files/2021/08/16/1375565/cach-nau-com-tam-suon-bi-cha-tai-nha-ngon-nhu-ngoai-tiem-202108162216045436.jpg', 'id_danh_muc' => '22'],
            ['id' => '77', 'ten_mon_an' => 'Sườn Chả', 'slug_mon_an' => 'suon-cha', 'gia_ban' => '30000', 'gia_khuyen_mai' => '25000', 'mo_ta' => '', 'id_quan_an' => '18', 'tinh_trang' => '1', 'hinh_anh' => 'https://comtambason.com/wp-content/uploads/2020/12/Suon-cha.png', 'id_danh_muc' => '22'],
            ['id' => '78', 'ten_mon_an' => 'Súp Cua', 'slug_mon_an' => 'sup-cua', 'gia_ban' => '25000', 'gia_khuyen_mai' => '20000', 'mo_ta' => '', 'id_quan_an' => '19', 'tinh_trang' => '1', 'hinh_anh' => 'https://cdn.tgdd.vn/2021/03/CookRecipe/GalleryStep/thanh-pham-353.jpg', 'id_danh_muc' => '9'],
            ['id' => '79', 'ten_mon_an' => 'Súp Bột Báng', 'slug_mon_an' => 'sup-bot-bang', 'gia_ban' => '25000', 'gia_khuyen_mai' => '20000', 'mo_ta' => '', 'id_quan_an' => '19', 'tinh_trang' => '1', 'hinh_anh' => 'https://thanhnien.mediacdn.vn/Uploaded/2014/Pictures201402/Thanh_Luan/2/botbang.jpg', 'id_danh_muc' => '9'],
            ['id' => '80', 'ten_mon_an' => 'Óc Heo Chưng', 'slug_mon_an' => 'oc-heo', 'gia_ban' => '25000', 'gia_khuyen_mai' => '20000', 'mo_ta' => '', 'id_quan_an' => '19', 'tinh_trang' => '1', 'hinh_anh' => 'https://cdn.tgdd.vn/2021/06/CookProduct/Oc-Heo-chung-gung-hanh-1200x676.jpg', 'id_danh_muc' => '44'],
            ['id' => '81', 'ten_mon_an' => 'Cháo Lòng', 'slug_mon_an' => 'chao-long', 'gia_ban' => '25000', 'gia_khuyen_mai' => '20000', 'mo_ta' => '', 'id_quan_an' => '20', 'tinh_trang' => '1', 'hinh_anh' => 'https://cdn.tgdd.vn/Files/2021/08/31/1379186/cong-thuc-mon-chao-long-doi-huyet-thom-ngon-hap-dan-kho-cuong-202201201119382365.jpg', 'id_danh_muc' => '44'],
            ['id' => '82', 'ten_mon_an' => 'Lòng Trộn', 'slug_mon_an' => 'long-tron', 'gia_ban' => '25000', 'gia_khuyen_mai' => '20000', 'mo_ta' => '', 'id_quan_an' => '20', 'tinh_trang' => '1', 'hinh_anh' => 'https://imgamp.phunutoday.vn/files/dataimages/201608/11/original/cach-lam-mon-goi-long-heo-tron-chua-cay-thom-ngon-tai-nha-phunutodayvn_1470934242.jpg', 'id_danh_muc' => '44'],
            ['id' => '83', 'ten_mon_an' => 'Lòng Nướng', 'slug_mon_an' => 'long-nuong', 'gia_ban' => '25000', 'gia_khuyen_mai' => '20000', 'mo_ta' => '', 'id_quan_an' => '20', 'tinh_trang' => '1', 'hinh_anh' => 'https://cdn.tgdd.vn/2020/10/CookProduct/61-1200x676.jpg', 'id_danh_muc' => '8'],
            ['id' => '84', 'ten_mon_an' => 'Lòng Hấp', 'slug_mon_an' => 'long-hap', 'gia_ban' => '25000', 'gia_khuyen_mai' => '20000', 'mo_ta' => '', 'id_quan_an' => '20', 'tinh_trang' => '1', 'hinh_anh' => 'https://pastaxi-manager.onepas.vn/content/uploads/articles/thanhmai/long-heo-hap-gung/long-heo-hap-gung%C4%83.jpg', 'id_danh_muc' => '44'],
        ]);
    }
}
