<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuanAnSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('quan_ans')->delete();
        DB::table('quan_ans')->truncate();
        DB::table('quan_ans')->insert([
            [
                'email' => 'nhahangA@gmail.com',
                'password' => 'password123',
                'ma_so_thue' => '0123456789',
                'ten_quan_an' => 'Nhà hàng Hải Sản Biển Đông',
                'dia_chi' => '123 Nguyễn Huệ, Quận 1',
                'so_dien_thoai' => '0901234567',
                'toa_do_x' => 10.7769,
                'toa_do_y' => 106.7009,
                'tinh_trang' => 1,
                'is_active' => 1,
                'gio_mo_cua' => '07:00',
                'gio_dong_cua' => '22:00',
                'id_tinh_thanh' => 2, // Giả sử 1 là TP.HCM
                'id_quan_huyen' => 1, // Giả sử 1 là Quận 1
            ],
            [
                'email' => 'nhahangB@gmail.com',
                'password' => 'password123',
                'ma_so_thue' => '0987654321',
                'ten_quan_an' => 'Quán Cơm Tấm Sài Gòn',
                'dia_chi' => '45 Lê Lợi, Quận 1',
                'so_dien_thoai' => '0912345678',
                'toa_do_x' => 10.7734,
                'toa_do_y' => 106.7033,
                'tinh_trang' => 1,
                'is_active' => 1,
                'gio_mo_cua' => '06:00',
                'gio_dong_cua' => '21:00',
                'id_tinh_thanh' => 2,
                'id_quan_huyen' => 1,
            ],
            [
                'email' => 'nhahangC@gmail.com',
                'password' => 'password123',
                'ma_so_thue' => '1234567890',
                'ten_quan_an' => 'Nhà hàng Phở Việt',
                'dia_chi' => '78 Võ Văn Tần, Quận 3',
                'so_dien_thoai' => '0923456789',
                'toa_do_x' => 10.7798,
                'toa_do_y' => 106.6917,
                'tinh_trang' => 1,
                'is_active' => 1,
                'gio_mo_cua' => '06:30',
                'gio_dong_cua' => '22:30',
                'id_tinh_thanh' => 2,
                'id_quan_huyen' => 3, // Giả sử 3 là Quận 3
            ],
            [
                'email' => 'nhahangD@gmail.com',
                'password' => 'password123',
                'ma_so_thue' => '2345678901',
                'ten_quan_an' => 'Quán Ốc Đêm',
                'dia_chi' => '234 Võ Thị Sáu, Quận 3',
                'so_dien_thoai' => '0934567890',
                'toa_do_x' => 10.7812,
                'toa_do_y' => 106.6892,
                'tinh_trang' => 1,
                'is_active' => 1,
                'gio_mo_cua' => '16:00',
                'gio_dong_cua' => '02:00',
                'id_tinh_thanh' => 2,
                'id_quan_huyen' => 3,
            ],
            [
                'email' => 'nhahangE@gmail.com',
                'password' => 'password123',
                'ma_so_thue' => '3456789012',
                'ten_quan_an' => 'Nhà hàng Buffet Sen',
                'dia_chi' => '567 Nguyễn Đình Chiểu, Quận 3',
                'so_dien_thoai' => '0945678901',
                'toa_do_x' => 10.7823,
                'toa_do_y' => 106.6901,
                'tinh_trang' => 1,
                'is_active' => 1,
                'gio_mo_cua' => '10:00',
                'gio_dong_cua' => '22:00',
                'id_tinh_thanh' => 2,
                'id_quan_huyen' => 3,
            ],
            [
                'email' => 'nhahangF@gmail.com',
                'password' => 'password123',
                'ma_so_thue' => '4567890123',
                'ten_quan_an' => 'Quán Bún Bò Huế',
                'dia_chi' => '89 Trần Hưng Đạo, Quận 5',
                'so_dien_thoai' => '0956789012',
                'toa_do_x' => 10.7534,
                'toa_do_y' => 106.6633,
                'tinh_trang' => 1,
                'is_active' => 1,
                'gio_mo_cua' => '06:00',
                'gio_dong_cua' => '21:00',
                'id_tinh_thanh' => 2,
                'id_quan_huyen' => 5,
            ],
            [
                'email' => 'nhahangG@gmail.com',
                'password' => 'password123',
                'ma_so_thue' => '5678901234',
                'ten_quan_an' => 'Quán Dimsum Tân Tân',
                'dia_chi' => '123 Trần Phú, Quận 5',
                'so_dien_thoai' => '0967890123',
                'toa_do_x' => 10.7523,
                'toa_do_y' => 106.6645,
                'tinh_trang' => 1,
                'is_active' => 1,
                'gio_mo_cua' => '08:00',
                'gio_dong_cua' => '21:00',
                'id_tinh_thanh' => 2,
                'id_quan_huyen' => 5,
            ],
            [
                'email' => 'nhahangH@gmail.com',
                'password' => 'password123',
                'ma_so_thue' => '6789012345',
                'ten_quan_an' => 'Quán Lẩu Dê',
                'dia_chi' => '456 Nguyễn Tri Phương, Quận 10',
                'so_dien_thoai' => '0978901234',
                'toa_do_x' => 10.7612,
                'toa_do_y' => 106.6723,
                'tinh_trang' => 1,
                'is_active' => 1,
                'gio_mo_cua' => '11:00',
                'gio_dong_cua' => '23:00',
                'id_tinh_thanh' => 2,
                'id_quan_huyen' => 10,
            ],
            [
                'email' => 'nhahangI@gmail.com',
                'password' => 'password123',
                'ma_so_thue' => '7890123456',
                'ten_quan_an' => 'Quán Cơm Niêu',
                'dia_chi' => '789 Sư Vạn Hạnh, Quận 10',
                'so_dien_thoai' => '0989012345',
                'toa_do_x' => 10.7634,
                'toa_do_y' => 106.6745,
                'tinh_trang' => 1,
                'is_active' => 1,
                'gio_mo_cua' => '10:00',
                'gio_dong_cua' => '21:00',
                'id_tinh_thanh' => 2,
                'id_quan_huyen' => 10,
            ],
            [
                'email' => 'nhahangJ@gmail.com',
                'password' => 'password123',
                'ma_so_thue' => '8901234567',
                'ten_quan_an' => 'Nhà hàng Chay Thiện Duyên',
                'dia_chi' => '321 Lý Thường Kiệt, Quận 10',
                'so_dien_thoai' => '0990123456',
                'toa_do_x' => 10.7645,
                'toa_do_y' => 106.6756,
                'tinh_trang' => 1,
                'is_active' => 1,
                'gio_mo_cua' => '07:00',
                'gio_dong_cua' => '20:00',
                'id_tinh_thanh' => 2,
                'id_quan_huyen' => 10,
            ],
        ]);
    }
}
